field.field_settings.priority_quadrant_priority:
  type: mapping
  label: 'Priority Item Settings'
  mapping:
    task:
      type: string
      label: 'Task'
    complexity:
      type: string
      label: 'Complexity'
    value:
      type: string
      label: 'Value'